import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/wagmiProvider/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FHEVM Next Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="grid place-items-center min-h-screen bg-main/15">
          <div className="h-full w-full grid md:max-w-6xl px-6 md:px-12">
            <Provider>{children}</Provider>
          </div>
        </main>
      </body>
    </html>
  );
}
